[package]
name = "gyromouse"
version = "0.1.0"
authors = ["Mikaël Fourrier <mikael.fourrier@pm.me>"]
edition = "2018"
resolver = "2"

[features]
default = ["sdl2"]
hidapi = ["hid-gamepad", "joycon"]
sdl2-static = ["sdl2", "sdl2/static-link", "sdl2/use-vcpkg"]
vgamepad = []
#vgamepad = ["virtual-gamepad"]

[dependencies]
anyhow = "1.0"
cgmath = "0.18"
clap = "3.0.0-beta.2"
enigo = "0.0"
# see https://gitlab.com/KonradBorowski/enum-map/-/issues/20
enum-map = "0.6"
hid-gamepad-types = { git = "https://github.com/Yamakaky/joy" }
hid-gamepad = { git = "https://github.com/Yamakaky/joy", optional = true }
joycon = { git = "https://github.com/Yamakaky/joy", optional = true }
nom = "6.2"
nom-supreme = "0.4"
#nom = { version = "6.2", path = "../nom", default-features = false }
#nom-supreme = { path = "../nom-supreme" }
#virtual-gamepad = { git = "https://github.com/Yamakaky/virtual-gamepad", optional = true }

[dependencies.sdl2]
git = "https://github.com/Yamakaky/rust-sdl2"
branch = "sensor-api"
optional = true 
default-features = false

[package.metadata.vcpkg]
dependencies = ["sdl2"]
git = "https://github.com/Yamakaky/vcpkg"
#branch = "sdl-hidapi"
branch = "sdl216-hidapi"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
